name: "go-srv"

on:
  push:
    tags: 
      - '*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
      - uses: action/checkout@v2
        name: checkout
      - name: get-version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: get-build-time
        run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}
      - name: get-build-commit
        run: echo "BUILD_COMMIT=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: 1.19
          md5sum: false
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: -X "main.appVersion=${{ env.RELEASE_VERSION }}" -X "main.buildTime=${{ env.BUILD_TIME }}" -X "main.buildCommit=${{ env.BUILD_COMMIT }}"
