name: "go-srv"

on: 
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
        name: checkout
      - uses: wangyoucao577/go-release-action@v1.53
        name: release-assets
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: 1.25
          md5sum: false
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}